apiVersion: v1
kind: Service
metadata:
  name: {{ include "adt-dummy.fullname" . }}
  labels:
    {{- include "adt-dummy.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "adt-dummy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
