{{- if (default true .Values.service.enabled) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "adt-dummy.fullname" . }}
  labels:
    {{- include "adt-dummy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ default .Values.service.port .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "adt-dummy.selectorLabels" . | nindent 4 }}
{{- end -}}
