replicaCount: 1

image:
  repository: artifactory.raiffeisen.ru/odt-docker/adt-dummy
  tag: "v0.1.0"
  pullPolicy: IfNotPresent
  pullSecrets:
    - artifactory-pull-secret

envFromSecret: "adt-dummy-secrets"

serviceAccount:
  create: true
  name: ""

podLabels: {}

env:
  ADT_DUMMY_IN_CLUSTER: "1"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
nodeSelector: {}
tolerations: []
affinity: {}
